@startuml

skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam defaultTextAlignment center
skinparam dpi 150
' up to down direction

interface Product {
     operate(): void
}

class ConcreteProduct {
    +attr: String 
     operate(): void
}

interface Creator {
     factoryMethod() : Product
}

class ConcreteCreator  {
     + factoryMethod(): Product
}



class Client {
    void operate()
}

ConcreteCreator .up|> Creator
ConcreteProduct .up|> Product
ConcreteCreator ..right> ConcreteProduct
Client  -[#white]> Product

Client ..down> Creator
Client ..down> Product
@enduml